kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-learning-cluster


nodes:
- role: control-plane
  image: kindest/node:v1.24.0
- role: worker
  image: kindest/node:v1.24.0
- role: worker
  image: kindest/node:v1.24.0
- role: worker
  image: kindest/node:v1.24.0
  extraPortMappings:
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    - containerPort: 8081
      hostPort: 8081
      protocol: TCP



# Command to Create kind cluster
# kind create cluster [cluster_name] --config=[config_file_name]

    