kind: Deployment
apiVersion: apps/v1

metadata:
  name: nginx-deployment
  namespace: custom-ns-nginx
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
    
  template:
    metadata:
      name: nginx-pod-by-deployment
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80