kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  namespace: custom-ns-nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80



# Commands
# kubectl apply -f KindCluster/pod.yml    -> To create Pods
# kubectl exec -it pod/[pod_name] -n [namespace_name] -- bash  -> To access the Pod and get into the pod